services:
  jabutta-web:
    container_name: jabutta-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    networks:
      - web

networks:
  web:
    external: true